# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Made2pay"
description: "Blog omtrent alles van Made2pay"
email: "niels@made2pay.com"
#blog logo
logo: "/assets/images/m2p_logo.jpg"
# blog cover
cover: "/assets/images/header_image.jpg"

name: 'Niels Koole'
author: 'Niels Koole'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://nielskoole.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: "@made2pay"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon: "twitter"
    url: "https://twitter.com/made2pay"
    desc: "Follow me on twitter"
    share_url: "http://twitter.com/share"
    share_title: "?text="
    share_link: "&amp;url="

  - icon: "facebook"
    url:	"https://facebook.com/made2pay"
    desc: "Connect with me facebook"
    share_url: "https://www.facebook.com/sharer.php"
    share_title: "?t="
    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/nielskoole
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
